-- Optional: Seed some sample clubs from the original data
-- Run this AFTER verifying tables exist
-- This will insert the clubs from src/data/clubs.ts into your database

INSERT INTO clubs (slug, name, short_desc, long_desc, room, category, advisor, contact_email, meeting_time, next_meeting, coordinates, socials) VALUES
('tech-club', 'Tech Club', 'Explore the latest in technology and build amazing projects together', 'Tech Club is your gateway to innovation. Whether you''re interested in coding, hardware, AI, or emerging tech trends, we provide hands-on workshops, guest speakers from the industry, and collaborative project opportunities.', 'VGLE8109', 'Technology', 'Dr. Tech Smith', 'techclub@piercecollege.edu', 'Mondays 1:00 PM - 2:00 PM PST', 'Monday, 1:00 PM', '{"lat": 34.185663, "lng": -118.573097}'::jsonb, NULL),
('shpe', 'SHPE (Society of Hispanic Professional Engineers)', 'Build an inclusive community that empowers students in STEM', 'To build an inclusive community that empowers and fosters students in STEM. We aim to help our members realize their fullest potential by providing personal growth through mentorship, leadership development, networking, educational support, and community engagement.', 'AT3804', 'Engineering', 'Prof. Maria Rodriguez', 'shpe@piercecollege.edu', 'Thursdays 2:00 PM - 3:00 PM PST', 'Thursday, 2:00 PM', '{"lat": 34.184705, "lng": -118.579943}'::jsonb, NULL),
('scientific-journal-club', 'Pierce Science Journal Club', 'Discuss cutting-edge scientific research and discoveries', 'Join us in exploring the latest scientific publications, discussing breakthrough research, and developing critical thinking skills. Perfect for aspiring scientists and curious minds alike.', 'CFS920321', 'Science', 'Dr. Sarah Johnson', 'sciencejournal@piercecollege.edu', 'Every other Friday 1:45 PM - 2:45 PM PST', 'Friday, 1:45 PM', '{"lat": 34.186134, "lng": -118.579714}'::jsonb, NULL),
('math-club', 'Math Club', 'Solve challenging problems and explore mathematical concepts', 'Dive into the fascinating world of mathematics! From number theory to calculus competitions, we make math fun and accessible for everyone.', 'MS2102', 'Mathematics', 'Prof. David Chen', 'mathclub@piercecollege.edu', 'Wednesdays 3:00 PM - 4:00 PM PST', 'Wednesday, 3:00 PM', NULL, NULL),
('physics-club', 'Physics Club', 'Explore the fundamental laws of the universe', 'From quantum mechanics to astrophysics, discover the wonders of physics through demonstrations, discussions, and hands-on experiments.', 'SC1204', 'Science', 'Dr. Robert Williams', 'physics@piercecollege.edu', 'Tuesdays 2:30 PM - 3:30 PM PST', 'Tuesday, 2:30 PM', NULL, NULL),
('api-club', 'API Club', 'Learn to build and integrate powerful APIs', 'Master the art of API development and integration. Build real-world projects, learn industry best practices, and connect applications together.', 'VGLE8105', 'Technology', 'Prof. Lisa Anderson', 'apiclub@piercecollege.edu', 'Fridays 12:00 PM - 1:00 PM PST', 'Friday, 12:00 PM', NULL, NULL),
('lego-club', 'LEGO Club', 'Build, create, and innovate with LEGO robotics', 'Combine creativity with engineering! Build LEGO robots, participate in competitions, and learn programming through hands-on projects.', 'EN1302', 'Engineering', 'Prof. Michael Brown', 'lego@piercecollege.edu', 'Thursdays 3:30 PM - 4:30 PM PST', 'Thursday, 3:30 PM', NULL, NULL),
('women-in-stem', 'Women in STEM', 'Empowering women to excel in science and technology', 'A supportive community for women pursuing careers in STEM. Network with professionals, attend workshops, and break barriers together.', 'SC2201', 'Science', 'Dr. Jennifer Lee', 'womeninstem@piercecollege.edu', 'Wednesdays 1:00 PM - 2:00 PM PST', 'Wednesday, 1:00 PM', NULL, NULL),
('girls-who-code', 'Girls Who Code', 'Learn coding in a supportive, inclusive environment', 'Join a global movement closing the gender gap in technology. Learn to code, build apps, and launch your tech career with an amazing community.', 'VGLE8201', 'Technology', 'Ms. Angela Martinez', 'girlswhocode@piercecollege.edu', 'Mondays 2:30 PM - 3:30 PM PST', 'Monday, 2:30 PM', NULL, NULL),
('engineering-club', 'Engineering Club', 'Design, build, and innovate engineering solutions', 'Get hands-on engineering experience through projects, competitions, and industry partnerships. All engineering disciplines welcome!', 'EN2401', 'Engineering', 'Prof. James Wilson', 'engineering@piercecollege.edu', 'Tuesdays 4:00 PM - 5:00 PM PST', 'Tuesday, 4:00 PM', NULL, NULL),
('chemistry-club', 'Chemistry Club', 'Experiment, discover, and explore the world of chemistry', 'Conduct exciting experiments, learn laboratory techniques, and discover how chemistry shapes our world. Safety goggles required!', 'CH1505', 'Science', 'Dr. Patricia Green', 'chemistry@piercecollege.edu', 'Fridays 2:00 PM - 3:00 PM PST', 'Friday, 2:00 PM', NULL, NULL),
('chess-club', 'Chess Club', 'Master strategy and compete in tournaments', 'Whether you''re a beginner or grandmaster, improve your chess skills, compete in tournaments, and enjoy the timeless game of strategy.', 'LB3102', 'Recreation', 'Prof. Alexander Ivanov', 'chess@piercecollege.edu', 'Wednesdays 4:00 PM - 5:30 PM PST', 'Wednesday, 4:00 PM', NULL, NULL)
ON CONFLICT (slug) DO NOTHING;

-- Verify the insert
SELECT COUNT(*) as total_clubs FROM clubs;

