// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --linked > src/integrations/supabase/types.ts
// Or manually copy from Supabase dashboard: Settings → API → TypeScript Types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          role: 'user' | 'admin' | 'advisor'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          role?: 'user' | 'admin' | 'advisor'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          role?: 'user' | 'admin' | 'advisor'
          created_at?: string
          updated_at?: string
        }
      }
      clubs: {
        Row: {
          id: string
          slug: string
          name: string
          short_desc: string
          long_desc: string | null
          room: string | null
          category: string
          advisor: string | null
          contact_email: string | null
          meeting_time: string | null
          next_meeting: string | null
          coordinates: Json | null
          socials: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          short_desc: string
          long_desc?: string | null
          room?: string | null
          category: string
          advisor?: string | null
          contact_email?: string | null
          meeting_time?: string | null
          next_meeting?: string | null
          coordinates?: Json | null
          socials?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          short_desc?: string
          long_desc?: string | null
          room?: string | null
          category?: string
          advisor?: string | null
          contact_email?: string | null
          meeting_time?: string | null
          next_meeting?: string | null
          coordinates?: Json | null
          socials?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      club_members: {
        Row: {
          id: string
          club_id: string
          user_id: string
          joined_at: string
        }
        Insert: {
          id?: string
          club_id: string
          user_id: string
          joined_at?: string
        }
        Update: {
          id?: string
          club_id?: string
          user_id?: string
          joined_at?: string
        }
      }
      events: {
        Row: {
          id: string
          club_id: string
          title: string
          description: string | null
          start_time: string
          end_time: string | null
          location: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          club_id: string
          title: string
          description?: string | null
          start_time: string
          end_time?: string | null
          location?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          club_id?: string
          title?: string
          description?: string | null
          start_time?: string
          end_time?: string | null
          location?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      event_attendees: {
        Row: {
          id: string
          event_id: string
          user_id: string
          checked_in_at: string
          checked_out_at: string | null
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          checked_in_at?: string
          checked_out_at?: string | null
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          checked_in_at?: string
          checked_out_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

